### ISSUE TITLE
Show map on single tree view and tree cluster view

### ISSUE THREAD

**Issue by xk0niR** [green-ecolution/green-ecolution-frontend#185]
When a tree or tree cluster is selected, add a map to easier remember it's position.

Example picture:
![Rastergrafik](https://github.com/user-attachments/assets/e01f63a4-04ff-413a-a86f-4bb78a9a91d7)

**Comment by doriengr** [comment]
I am closing this issue because we implemented the »Auf Karte anzeigen« Button 👍
