### ISSUE TITLE
Tree cluster without region is not visible on map

### ISSUE THREAD

**Issue by xk0niR** [green-ecolution/green-ecolution-frontend#229]
ref #227 

If a tree cluster has no region there is no indicator about the cluster on the map.
Inside tree cluster view the option "Auf der Karte anzeigen" still opens the correct location but no cluster is visible.

**Comment by xk0niR** [comment]
![noTreeClusterVisible-opt](https://github.com/user-attachments/assets/1bc5bc53-6374-4f35-a145-669bc87b44dc)

**Comment by doriengr** [comment]
This is closed by this PR https://github.com/green-ecolution/green-ecolution-frontend/pull/252
